describe("Cloud assignment parsing", function()
    before_each(run_before)

    it("parses assignment list from cloud JSON", function()
        step("cloud assignment JSON")
        step("I parse assignment list from JSON")
        step("there should be 1 assignment")
        step('assignment job id should be "job-7f3a"')
        step("assignment step count should be 2")
        step('assignment step 1 type should be "wait"')
        step('assignment step 2 type should be "transfer"')
    end)

    it("resolves registry keys through HardwareContext", function()
        step("cloud assignment JSON")
        step("I parse assignment list from JSON")
        step("a registry from the parsed assignment")
        step('hardware context should resolve transposer to "def-456"')
        step("I load machine from hardware context")
        step('machine address should be "abc-123"')
    end)
end)

describe("Executor step sequences", function()
    before_each(run_before)

    it("completes wait-only sequence", function()
        step("a wait-only assignment with 2 steps")
        step("I begin the executor")
        step("the executor ticks until inactive")
        step('the executor phase should be "DONE"')
        step("the result should be ok")
    end)

    it("completes wait ticks sequence", function()
        step("a wait assignment with 2 ticks")
        step("I begin the executor")
        step("the executor ticks until inactive")
        step('the executor phase should be "DONE"')
        step("the result should be ok")
    end)

    it("completes transfer sequence", function()
        step("a transfer assignment with sides")
        step("I begin the executor")
        step("the executor ticks until inactive")
        step('the executor phase should be "DONE"')
        step("the result should be ok")
    end)

    it("completes configure and clear sequence", function()
        step("a configure and clear assignment")
        step("I begin the executor")
        step("the executor ticks until inactive")
        step('the executor phase should be "DONE"')
        step("the result should be ok")
    end)

    it("completes process poll when machine stops", function()
        step("a process assignment with timeout 10")
        step("machine is active during process step")
        step("I begin the executor")
        step("the executor ticks 2 times")
        step("machine becomes inactive")
        step("the executor ticks 2 times")
        step('the executor phase should be "DONE"')
        step("the result should be ok")
    end)

    it("faults transfer without sides", function()
        step("a transfer assignment missing fromSide and toSide")
        step("I begin the executor")
        step("the executor ticks once")
        step('the executor phase should be "FAULTED"')
    end)

    it("faults when transfer moves zero items", function()
        step("a transfer assignment with sides and zero moved")
        step("I begin the executor")
        step("the executor ticks until inactive")
        step('the executor phase should be "FAULTED"')
    end)
end)
