describe("Cloud assignment parsing", function()
    before_each(run_before)

    it("parses assignment list from cloud JSON", function()
        step("cloud assignment JSON")
        step("I parse assignment list from JSON")
        step("there should be 1 assignment")
        step('assignment job id should be "job-7f3a"')
        step("assignment step count should be 2")
        step('assignment step 1 type should be "wait"')
        step('assignment step 2 type should be "transfer"')
    end)
end)
