describe("Job pool concurrency", function()
    before_each(run_before)

    it("runs concurrent jobs on two machines", function()
        step("an empty job pool")
        step('I spawn job "job-A" on "machine-lathe"')
        step("spawn should succeed")
        step("active job count should be 1")
        step('I spawn job "job-B" on "machine-assembler"')
        step("spawn should succeed")
        step("active job count should be 2")
        step('I spawn job "job-A-dup" on "machine-lathe"')
        step("spawn should fail")
        step("I tick the job pool until 2 jobs complete")
        step("completed jobs count should be 2")
        step("faulted jobs count should be 0")
    end)
end)
