describe("Module loading and hardware parsing", function()
    before_each(run_before)

    it("loads all AE2-ES2 modules", function()
        step("all AE2-ES2 modules are loadable")
    end)

    it("parses machine sensor processing state", function()
        step("a machine with processing sensor lines")
        step("I parse machine sensor information")
        step("machine progress should be 32 of 75")
        step("machine availability should be unavailable due to processing")
    end)

    it("parses machine sensor problems", function()
        step("a machine with sensor problems 2")
        step("I parse machine sensor information")
        step("machine availability should be unavailable due to problems")
    end)

    it("formats zero-indexed ME items and fluids", function()
        step("I format zero-indexed ME items")
        step("formatted items count should be 2")
        step("I format zero-indexed ME fluids")
        step("formatted fluids count should be 2")
        step("I format iterator-style ME items")
        step("formatted items count should be 1")
    end)

    it("reads ME controller buffer snapshot", function()
        step("I read ME controller buffer snapshot")
        step("buffer snapshot should have at least 1 items and 1 fluids")
    end)
end)
