describe("Node sensor discovery", function()
    before_each(run_before)

    it("discovers machines and merges busy flags", function()
        step("a node sensor with ME controller")
        step("I scan machines")
        step("discovered machine count should be 2")
        step('job pool has busy machine "machine-lathe"')
        step("I merge job pool busy flags")
        step('machine "machine-lathe" should be busy')
        step("I tick node sensor")
        step("node sensor should have pending request")
        step("buffer snapshot should have at least 1 items")
    end)
end)
